<?xml  version="1.0" encoding="utf-8" ?>
<!-- 文档类型定义 -->
<!--
* 表示可以有0-n个
-->
<!DOCTYPE beans [
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref  IDREF #IMPLIED >
]>
<beans>
    <!-- dao层 -->
    <bean id="userBasicDao" class="come.hhj.qqzone.dao.imp.UserBasicDAOImp">  </bean>
    <bean id="topicDao" class="come.hhj.qqzone.dao.imp.TopicDAOImp">  </bean>

    <!-- 业务层 -->
    <bean id="userBasicService" class="come.hhj.qqzone.service.impl.UserBasicServiceImpl">
        <property name="userBasicDao" ref="userBasicDao" />
    </bean>
    <bean id="topicService" class="come.hhj.qqzone.service.impl.TopicServiceImpl">
        <property name="topicDao" ref="topicDao"/>
    </bean>

    <!-- 控制层 -->
    <bean id="user" class="come.hhj.qqzone.Controller.UserController">
        <property name="userBasicService" ref="userBasicService" />
        <property name="topicService" ref="topicService" />
    </bean>

    <bean id="page" class="come.hhj.myssm.myspringmvc.PageController">
    </bean>
</beans>





