<?xml  version="1.0" encoding="utf-8" ?>
<!-- 文档类型定义 -->
<!--
* 表示可以有0-n个
-->
<!DOCTYPE beans [
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property name CDATA #IMPLIED>
        <!ATTLIST property ref  IDREF #IMPLIED >
]>
<beans>
    <!-- DAO 层 -->
    <bean id="userDao" class="com.hhj.book.dao.impl.UserDAOImpl"/>
    <bean id="bookDao" class="com.hhj.book.dao.impl.BookDaoImpl"/>
    <bean id="cartDao" class="com.hhj.book.dao.impl.CartBookImpl"/>
    <bean id="orderDao" class="com.hhj.book.dao.impl.OrderDaoImpl"/>
    <bean id="orderItemDao" class="com.hhj.book.dao.impl.OrderItemDaoimp"/>


    <!-- Service 层 -->
    <bean id="userService" class="com.hhj.book.service.impl.UserServiceImpl">
        <property name="userDao" ref="userDao" />
    </bean>
    <bean id="bookService" class="com.hhj.book.service.impl.BookServiceImpl">
        <property name="bookDao" ref="bookDao" />
    </bean>
    <bean id="cartService" class="com.hhj.book.service.impl.CartServiceImpl">
        <property name="cartDao" ref="cartDao" />
        <property name="bookService" ref="bookService" />
    </bean>
    <bean id="orderService" class="com.hhj.book.service.impl.OrderServiceImpl">
        <property name="orderDao" ref="orderDao" />
        <property name="cartService" ref="cartService" />
        <property name="orderItemService" ref="orderItemService" />
    </bean>
    <bean id="orderItemService" class="com.hhj.book.service.impl.OrderItemServiceImpl">
        <property name="orderItemDao" ref="orderItemDao" />
    </bean>



    <!-- controller 层 -->
    <bean id="user" class="com.hhj.book.controller.UserController">
        <property name="userService" ref="userService" />
    </bean>
    <bean id="book" class="com.hhj.book.controller.BookController">
        <property name="bookService" ref="bookService" />
    </bean>
    <bean id="cart" class="com.hhj.book.controller.CartController">
        <property name="cartService" ref="cartService" />
    </bean>
    <bean id="order" class="com.hhj.book.controller.OrderController">
        <property name="orderService" ref="orderService" />
    </bean>


    <bean id="page" class="com.hhj.myssm.myspringmvc.PageController"/>

</beans>





